export const BACKGROUND_CANVAS: HTMLCanvasElement = window.document.getElementById('background') as HTMLCanvasElement;
export const BRICK_CANVAS: HTMLCanvasElement = window.document.getElementById('brick') as HTMLCanvasElement;
export const GAME_CANVAS: HTMLCanvasElement = window.document.getElementById('game') as HTMLCanvasElement;

export const GRID_SIZE: number = 26;
export const SPRITE_SCALE: number = 600 / 208;
export const FULL_CIRCLE: number = Math.PI * 2;
export const RADIANS_PER_DEGREE: number = Math.PI / 180.0;

export enum CONSTS {
	DIRECTION_UP,
	DIRECTION_RIGHT,
	DIRECTION_DOWN,
	DIRECTION_LEFT,

	TANK_PLAYER1,
	TANK_PLAYER2,
	TANK_ENEMY_BASIC,
	TANK_ENEMY_FAST,
	TANK_ENEMY_POWER,
	TANK_ENEMY_ARMOR,

	TANK_POWER_NONE,
	TANK_POWER_1STAR,
	TANK_POWER_2STARS,
	TANK_POWER_3STARS,
	TANK_POWER_DROPSPOWERUP,

	STRUCTURE_BRICK,
	STRUCTURE_STEEL,
	STRUCTURE_FLAG,

	STRUCTURE_WHOLE,
	STRUCTURE_LEFT_GONE,
	STRUCTURE_TOP_GONE,
	STRUCTURE_BOTTOM_GONE,
	STRUCTURE_RIGHT_GONE,
	STRUCTURE_ALL_GONE,

	TERRAIN_WATER,
	TERRAIN_TREES,
	TERRAIN_ICE,
	TERRAIN_BLANK,

	POWERUP_HELMET,
	POWERUP_TIMER,
	POWERUP_SHOVEL,
	POWERUP_STAR,
	POWERUP_GRENADE,
	POWERUP_TANK,

	EFFECT_SPAWNFLASH,
	EFFECT_SMALLEXPLOSION,
	EFFECT_LARGEEXPLOSION,
	EFFECT_INVULNERABLE,
	EFFECT_POINTS,

	BULLET,
	BORDER,
}
